# Generated by Django 5.2.7 on 2025-11-03 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('season', models.IntegerField(db_index=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('toss_winner', models.CharField(blank=True, max_length=100, null=True)),
                ('toss_decision', models.CharField(blank=True, max_length=10, null=True)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('dl_applied', models.IntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('win_by_runs', models.IntegerField(blank=True, null=True)),
                ('win_by_wickets', models.IntegerField(blank=True, null=True)),
                ('player_of_match', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('umpire1', models.CharField(blank=True, max_length=100, null=True)),
                ('umpire2', models.CharField(blank=True, max_length=100, null=True)),
                ('umpire3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['season', 'match_id'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inning', models.IntegerField()),
                ('batting_team', models.CharField(max_length=100)),
                ('bowling_team', models.CharField(max_length=100)),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('batsman', models.CharField(blank=True, max_length=200, null=True)),
                ('non_striker', models.CharField(blank=True, max_length=200, null=True)),
                ('bowler', models.CharField(max_length=200)),
                ('is_super_over', models.IntegerField(blank=True, null=True)),
                ('wide_runs', models.IntegerField(blank=True, null=True)),
                ('bye_runs', models.IntegerField(blank=True, null=True)),
                ('legbye_runs', models.IntegerField(blank=True, null=True)),
                ('noball_runs', models.IntegerField(blank=True, null=True)),
                ('penalty_runs', models.IntegerField(blank=True, null=True)),
                ('batsman_runs', models.IntegerField(blank=True, null=True)),
                ('extra_runs', models.IntegerField(blank=True, null=True)),
                ('total_runs', models.IntegerField(blank=True, null=True)),
                ('player_dismissed', models.CharField(blank=True, max_length=200, null=True)),
                ('dismissal_kind', models.CharField(blank=True, max_length=100, null=True)),
                ('fielder', models.CharField(blank=True, max_length=200, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.match')),
            ],
            options={
                'db_table': 'deliveries',
                'indexes': [models.Index(fields=['bowler'], name='deliveries_bowler_cc9783_idx'), models.Index(fields=['bowling_team'], name='deliveries_bowling_e0e97d_idx'), models.Index(fields=['match'], name='deliveries_match_i_92abc2_idx')],
            },
        ),
    ]
